/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';
import {
  GQAAppState,
} from './components/admin/utils/GQAAppState';


export namespace Components {

  interface GqaAdminPage {}
  interface GqaAdminPageAttributes extends StencilHTMLAttributes {}

  interface GqaErrorView {}
  interface GqaErrorViewAttributes extends StencilHTMLAttributes {}

  interface GqaFormComponent {
    'appState': GQAAppState;
    'side': String;
  }
  interface GqaFormComponentAttributes extends StencilHTMLAttributes {
    'appState'?: GQAAppState;
    'side'?: String;
  }

  interface GqaErrorMessage {
    'error': any;
  }
  interface GqaErrorMessageAttributes extends StencilHTMLAttributes {
    'error'?: any;
  }

  interface GqaHeader {}
  interface GqaHeaderAttributes extends StencilHTMLAttributes {}

  interface GqaListComponent {
    'appState': GQAAppState;
    'side': String;
  }
  interface GqaListComponentAttributes extends StencilHTMLAttributes {
    'appState'?: GQAAppState;
    'onRightRowSelected'?: (event: CustomEvent) => void;
    'side'?: String;
  }

  interface GqaListHeader {}
  interface GqaListHeaderAttributes extends StencilHTMLAttributes {}

  interface GqaListItemComponent {}
  interface GqaListItemComponentAttributes extends StencilHTMLAttributes {}

  interface GqaMainView {
    'appState': GQAAppState;
    'side': String;
  }
  interface GqaMainViewAttributes extends StencilHTMLAttributes {
    'appState'?: GQAAppState;
    'side'?: String;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface GqaAdminMenu {}
  interface GqaAdminMenuAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'GqaAdminPage': Components.GqaAdminPage;
    'GqaErrorView': Components.GqaErrorView;
    'GqaFormComponent': Components.GqaFormComponent;
    'GqaErrorMessage': Components.GqaErrorMessage;
    'GqaHeader': Components.GqaHeader;
    'GqaListComponent': Components.GqaListComponent;
    'GqaListHeader': Components.GqaListHeader;
    'GqaListItemComponent': Components.GqaListItemComponent;
    'GqaMainView': Components.GqaMainView;
    'AppRoot': Components.AppRoot;
    'GqaAdminMenu': Components.GqaAdminMenu;
  }

  interface StencilIntrinsicElements {
    'gqa-admin-page': Components.GqaAdminPageAttributes;
    'gqa-error-view': Components.GqaErrorViewAttributes;
    'gqa-form-component': Components.GqaFormComponentAttributes;
    'gqa-error-message': Components.GqaErrorMessageAttributes;
    'gqa-header': Components.GqaHeaderAttributes;
    'gqa-list-component': Components.GqaListComponentAttributes;
    'gqa-list-header': Components.GqaListHeaderAttributes;
    'gqa-list-item-component': Components.GqaListItemComponentAttributes;
    'gqa-main-view': Components.GqaMainViewAttributes;
    'app-root': Components.AppRootAttributes;
    'gqa-admin-menu': Components.GqaAdminMenuAttributes;
  }


  interface HTMLGqaAdminPageElement extends Components.GqaAdminPage, HTMLStencilElement {}
  var HTMLGqaAdminPageElement: {
    prototype: HTMLGqaAdminPageElement;
    new (): HTMLGqaAdminPageElement;
  };

  interface HTMLGqaErrorViewElement extends Components.GqaErrorView, HTMLStencilElement {}
  var HTMLGqaErrorViewElement: {
    prototype: HTMLGqaErrorViewElement;
    new (): HTMLGqaErrorViewElement;
  };

  interface HTMLGqaFormComponentElement extends Components.GqaFormComponent, HTMLStencilElement {}
  var HTMLGqaFormComponentElement: {
    prototype: HTMLGqaFormComponentElement;
    new (): HTMLGqaFormComponentElement;
  };

  interface HTMLGqaErrorMessageElement extends Components.GqaErrorMessage, HTMLStencilElement {}
  var HTMLGqaErrorMessageElement: {
    prototype: HTMLGqaErrorMessageElement;
    new (): HTMLGqaErrorMessageElement;
  };

  interface HTMLGqaHeaderElement extends Components.GqaHeader, HTMLStencilElement {}
  var HTMLGqaHeaderElement: {
    prototype: HTMLGqaHeaderElement;
    new (): HTMLGqaHeaderElement;
  };

  interface HTMLGqaListComponentElement extends Components.GqaListComponent, HTMLStencilElement {}
  var HTMLGqaListComponentElement: {
    prototype: HTMLGqaListComponentElement;
    new (): HTMLGqaListComponentElement;
  };

  interface HTMLGqaListHeaderElement extends Components.GqaListHeader, HTMLStencilElement {}
  var HTMLGqaListHeaderElement: {
    prototype: HTMLGqaListHeaderElement;
    new (): HTMLGqaListHeaderElement;
  };

  interface HTMLGqaListItemComponentElement extends Components.GqaListItemComponent, HTMLStencilElement {}
  var HTMLGqaListItemComponentElement: {
    prototype: HTMLGqaListItemComponentElement;
    new (): HTMLGqaListItemComponentElement;
  };

  interface HTMLGqaMainViewElement extends Components.GqaMainView, HTMLStencilElement {}
  var HTMLGqaMainViewElement: {
    prototype: HTMLGqaMainViewElement;
    new (): HTMLGqaMainViewElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLGqaAdminMenuElement extends Components.GqaAdminMenu, HTMLStencilElement {}
  var HTMLGqaAdminMenuElement: {
    prototype: HTMLGqaAdminMenuElement;
    new (): HTMLGqaAdminMenuElement;
  };

  interface HTMLElementTagNameMap {
    'gqa-admin-page': HTMLGqaAdminPageElement
    'gqa-error-view': HTMLGqaErrorViewElement
    'gqa-form-component': HTMLGqaFormComponentElement
    'gqa-error-message': HTMLGqaErrorMessageElement
    'gqa-header': HTMLGqaHeaderElement
    'gqa-list-component': HTMLGqaListComponentElement
    'gqa-list-header': HTMLGqaListHeaderElement
    'gqa-list-item-component': HTMLGqaListItemComponentElement
    'gqa-main-view': HTMLGqaMainViewElement
    'app-root': HTMLAppRootElement
    'gqa-admin-menu': HTMLGqaAdminMenuElement
  }

  interface ElementTagNameMap {
    'gqa-admin-page': HTMLGqaAdminPageElement;
    'gqa-error-view': HTMLGqaErrorViewElement;
    'gqa-form-component': HTMLGqaFormComponentElement;
    'gqa-error-message': HTMLGqaErrorMessageElement;
    'gqa-header': HTMLGqaHeaderElement;
    'gqa-list-component': HTMLGqaListComponentElement;
    'gqa-list-header': HTMLGqaListHeaderElement;
    'gqa-list-item-component': HTMLGqaListItemComponentElement;
    'gqa-main-view': HTMLGqaMainViewElement;
    'app-root': HTMLAppRootElement;
    'gqa-admin-menu': HTMLGqaAdminMenuElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
