/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';
import {
  GAState,
} from './components/admin/ga-utils/GAState';
import {
  GAModel,
} from './components/admin/ga-utils/GAModel';


export namespace Components {

  interface GaForm {
    'appState': GAState;
    'model': GAModel;
    'side': String;
  }
  interface GaFormAttributes extends StencilHTMLAttributes {
    'appState'?: GAState;
    'model'?: GAModel;
    'onFormSubmittedEvent'?: (event: CustomEvent) => void;
    'onModelUpdated'?: (event: CustomEvent) => void;
    'onSubTableSelected'?: (event: CustomEvent) => void;
    'side'?: String;
  }

  interface GaList {
    'appState': GAState;
    'model': GAModel;
    'side': String;
  }
  interface GaListAttributes extends StencilHTMLAttributes {
    'appState'?: GAState;
    'model'?: GAModel;
    'onLeftRowSelected'?: (event: CustomEvent) => void;
    'onRightRowSelected'?: (event: CustomEvent) => void;
    'side'?: String;
  }

  interface GraphqlAdmin {}
  interface GraphqlAdminAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface GaAdminMenu {}
  interface GaAdminMenuAttributes extends StencilHTMLAttributes {
    'onNavTo'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'GaForm': Components.GaForm;
    'GaList': Components.GaList;
    'GraphqlAdmin': Components.GraphqlAdmin;
    'AppRoot': Components.AppRoot;
    'GaAdminMenu': Components.GaAdminMenu;
  }

  interface StencilIntrinsicElements {
    'ga-form': Components.GaFormAttributes;
    'ga-list': Components.GaListAttributes;
    'graphql-admin': Components.GraphqlAdminAttributes;
    'app-root': Components.AppRootAttributes;
    'ga-admin-menu': Components.GaAdminMenuAttributes;
  }


  interface HTMLGaFormElement extends Components.GaForm, HTMLStencilElement {}
  var HTMLGaFormElement: {
    prototype: HTMLGaFormElement;
    new (): HTMLGaFormElement;
  };

  interface HTMLGaListElement extends Components.GaList, HTMLStencilElement {}
  var HTMLGaListElement: {
    prototype: HTMLGaListElement;
    new (): HTMLGaListElement;
  };

  interface HTMLGraphqlAdminElement extends Components.GraphqlAdmin, HTMLStencilElement {}
  var HTMLGraphqlAdminElement: {
    prototype: HTMLGraphqlAdminElement;
    new (): HTMLGraphqlAdminElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLGaAdminMenuElement extends Components.GaAdminMenu, HTMLStencilElement {}
  var HTMLGaAdminMenuElement: {
    prototype: HTMLGaAdminMenuElement;
    new (): HTMLGaAdminMenuElement;
  };

  interface HTMLElementTagNameMap {
    'ga-form': HTMLGaFormElement
    'ga-list': HTMLGaListElement
    'graphql-admin': HTMLGraphqlAdminElement
    'app-root': HTMLAppRootElement
    'ga-admin-menu': HTMLGaAdminMenuElement
  }

  interface ElementTagNameMap {
    'ga-form': HTMLGaFormElement;
    'ga-list': HTMLGaListElement;
    'graphql-admin': HTMLGraphqlAdminElement;
    'app-root': HTMLAppRootElement;
    'ga-admin-menu': HTMLGaAdminMenuElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
